spring:
  application:
    name: api-bs-v1
  webflux:
    base-path: /api/bs-v1
    
springdoc:
  info:
    version: '@project.version@'
    title: '@project.artifactId@'
    description: '@project.description@'
    servers:
      - 'http://localhost:8082/'
      - 'http://localhost/'
  api-docs:
    path: /openapi
    yaml:
      enabled: true    
  swagger-ui:
    enabled: false    