server:
  port: 8081
spring:
  devtools:
    livereload:
      enabled: true
      port: 3574
  data:
    redis:
      host: localhost
      port: 6379
http-client:
  api-data-v1:
    base-url: http://localhost:8082/api/data-v1
    timeout: 5000
validation:
  password:
    pattern: ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z0-9]{8,}$
security:
  jwt:
    secret: 5b87002b7468120df2e1dbbd223caf54e9cfbf0800f084380bc1d1d84f747bb897a9bfae51b868a0cf2d0f5094c0e07a07f6a49f2fdb395c37e7186cab6d00f0
    expiration: 86400000
    rol: ADMIN